# DEFAULT CONFIG FILE: PLEASE MAKE A COPY TO RUN CUSTOM SCRIPTS 

# config.yml

# Device
cuda: true  # override if you wish to disable CUDA

# MODEL ARCHITECTURE
model: "GIN"               # choices: "GIN", "GIN2", "RecurrentGIN", "GlobalGIN", "MLP", "harmonic"
GIN_params:
  num_layers: 8
  num_mlp_layers: 3
  hidden_dim: 60
  dropout: 0.1 
GIN2_params:
  num_layers: 8
  num_mlp_layers: 3
  hidden_dim: 60
  global_dim: 10
  dropout: 0.1 
RecurrentGIN_params: 
  num_mlp_layers: 3
  hidden_dim: 30
  global_dim: 5
  dropout: 0.1 
GlobalGIN_params: 
  num_layers: 8
  num_mlp_layers: 3
  hidden_dim: 60
  dropout: 0.1 
MLP_params:
  num_layers: 8
  hidden_dim: 60
  dropout: 0.1 



use_bias: true

lr: 0.01
weight_decay: 0.005
patience: 10
epochs: 200
use_early_stopping: false
multiple_runs: false
num_of_runs: 100
follow_paper: true

# LOSS FUNCTIONS
energy: false
supervised_eigval: false
supervised_eigval_unweighted: false
supervised_lap_reconstruction: false
supervised_mse: false

forced_ortho: false
lambda_energy: 50
lambda_ortho: 1

# EMBEDDINGS
diffusion_emb: false
diffusion_row: false
wavelet_emb: false
scatter_emb: false
global_scatter_emb: false
invariance_transform: "none"   # choices: "none", "random", "forced_order"
wavelet_moments_emb: false
neighbor_bump_emb: false
diffused_dirac_emb: false

# DATASET LOADING: preprocessing (delete "processed" folder to recompute from scratch if you are changing settings)
use_supervised: false
use_largest_connected_components: true

# DATASET LOADING: per-run
use_mini_dataset: 1.0

# MODEL LOAD / SAVE PATHS
checkpoint_folder: # Only change this if you want a custom folder name, otherwise defaults to match the name of this config file
 
load_model: null                # path to a saved model, or null

# ACTIONS
train: false
test: false

# DATA
dataset: "ogbg_ppa"            # choices: "ogbg_ppa", "zinc"
evec_len: 300
num_eigenvectors: 30

