# DEFAULT CONFIG FILE: PLEASE MAKE A COPY TO RUN CUSTOM SCRIPTS 

# config.yml

# Device
cuda: true  # override if you wish to disable CUDA

# MODEL ARCHITECTURE
model: "GIN"               
# choices (trainable): "GIN", "GIN2", "RecurrentGIN", "GlobalGIN", "MLP", "MLP2", "GlobalMLP"
# choices (analytic methods, do NOT train): harmonic", "lanczos", "ground_truth", "random_vectors"

GIN_params:
  num_layers: 8
  num_mlp_layers: 3
  hidden_dim: 60
  dropout: 0.1 
GIN2_params:
  num_layers: 8
  num_mlp_layers: 3
  hidden_dim: 60
  global_dim: 10
  dropout: 0.1 
RecurrentGIN_params: 
  num_mlp_layers: 3
  hidden_dim: 30
  global_dim: 5
  dropout: 0.1
GlobalGIN_params: 
  num_layers: 4
  num_mlp_layers: 3
  final_mlp_layers: 5
  hidden_dim: 60
  dropout: 0.1 
  use_attention: true
MLP_params:
  num_layers: 8
  hidden_dim: 60
MLP2_params:
  num_layers: 8
  hidden_dim: 60
  dropout: 0.1
harmonic_params:
  subspace_size: # Note: if left empty, will choose to be 2* num_eigenvectors
lanczos_params:
  subspace_size: # Note: if left empty, will choose to be 2* num_eigenvectors
random_params:
  num_samples: 1000



use_bias: true

lr: 0.01
weight_decay: 0.005
patience: 10
epochs: 200
use_early_stopping: false
multiple_runs: false
num_of_runs: 100
follow_paper: true

# LOSS FUNCTIONS
energy: false
supervised_eigval: false
supervised_eigval_unweighted: false
supervised_lap_reconstruction: false
supervised_mse: false

#WEIGHTS FOR MIXED LOSS FUNCTIONS
energy_weight: 1
eigval_weight: 1


forced_ortho: false

lambda_energy: 1
lambda_supervised_eigval: 2
lambda_ortho: 1

# EMBEDDINGS
diffusion_emb: false
diffusion_row: false
wavelet_emb: true
wavelet_positional_emb: false
scatter_emb: false
global_scatter_emb: false
invariance_transform: "none"   # choices: "none", "random", "forced_order"
wavelet_moments_emb: false
neighbor_bump_emb: false
diffused_dirac_emb: false

# DATASET LOADING: preprocessing (delete "processed" folder to recompute from scratch if you are changing settings)
use_supervised: false
use_largest_connected_components: true

# DATASET LOADING: per-run
use_mini_dataset: 1.0

# MODEL LOAD / SAVE PATHS
checkpoint_folder: # Only change this if you want a custom folder name, otherwise defaults to match the name of this config file
 
load_model: null                # path to a saved model, or null

# ACTIONS
train: false 
test: false

# DATA
dataset: "ogbg_ppa"            # choices: "ogbg_ppa", "zinc"
num_eigenvectors: 30

